/**:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false

    odom1: /odom/wheel
    odom1_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_nodelay: false

    odom2: /rtabmap/odom
    odom2_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom2_queue_size: 10
    odom2_nodelay: false

    odom3: /lidar_odom
    odom3_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom3_queue_size: 10
    odom3_nodelay: false

    odom4: /vo
    odom4_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom4_queue_size: 10
    odom4_nodelay: false

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_queue_size: 50
    imu0_nodelay: false
    imu0_remove_gravitational_acceleration: true

    use_control: false
    stamped_control: false
    control_timeout: 0.2
    acceleration_limits: [0.0, 0.0, 0.0]
    deceleration_limits: [0.0, 0.0, 0.0]
    control_config: [true, false, false, false, false, true]

    print_diagnostics: true
